"""added scrape constraint

Revision ID: 201a2f5a2ad4
Revises: bf9f26a65d8b
Create Date: 2024-01-24 16:58:05.182452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201a2f5a2ad4'
down_revision = 'bf9f26a65d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('date_location_sc', ['location', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_data', schema=None) as batch_op:
        batch_op.drop_constraint('date_location_sc', type_='unique')

    # ### end Alembic commands ###
