"""added users table

Revision ID: 4ad5e95d42fc
Revises: dd89db24b94f
Create Date: 2024-01-25 15:20:32.897002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad5e95d42fc'
down_revision = 'dd89db24b94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
