"""added scrape constraint

Revision ID: 6ed1f1c97c3c
Revises: 201a2f5a2ad4
Create Date: 2024-01-24 17:02:29.020914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed1f1c97c3c'
down_revision = '201a2f5a2ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_data', schema=None) as batch_op:
        batch_op.drop_constraint('date_location_sc', type_='unique')
        batch_op.create_unique_constraint('date_location_sc', ['location', 'date', 'manufacturer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_data', schema=None) as batch_op:
        batch_op.drop_constraint('date_location_sc', type_='unique')
        batch_op.create_unique_constraint('date_location_sc', ['location', 'date'])

    # ### end Alembic commands ###
