"""added created_at

Revision ID: bf9f26a65d8b
Revises: f19173bf157b
Create Date: 2024-01-24 15:44:06.684745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9f26a65d8b'
down_revision = 'f19173bf157b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_data', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
