"""added unique constraint

Revision ID: f19173bf157b
Revises: d792aeb44fb8
Create Date: 2024-01-24 15:10:37.902226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19173bf157b'
down_revision = 'd792aeb44fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('date_location_uc', ['location', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_data', schema=None) as batch_op:
        batch_op.drop_constraint('date_location_uc', type_='unique')

    # ### end Alembic commands ###
